Small fix for pagenation with jobs more than 1000 frames (#1471)
When jobs have more then 1000 frames it fails to pagenate and throws
this :
```python
Traceback (most recent call last):
  File "/home/jimmy/repos/OpenCue/cuegui/cuegui/plugins/MonitorJobDetailsPlugin.py", line 96, in handleLayerFilter
    self.__monitorFrames.filterLayersFromDoubleClick(names)
  File "/home/jimmy/repos/OpenCue/cuegui/cuegui/FrameMonitor.py", line 116, in filterLayersFromDoubleClick
    self._filterLayersHandleByLayer(layerNames)
  File "/home/jimmy/repos/OpenCue/cuegui/cuegui/FrameMonitor.py", line 413, in _filterLayersHandleByLayer
    self._updatePageButtonState()
  File "/home/jimmy/repos/OpenCue/cuegui/cuegui/FrameMonitor.py", line 277, in _updatePageButtonState
    temp_frames = job.getFrames(temp_search)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Job.getFrames() takes 1 positional argument but 2 were given
```

**Summarize your change.**
Passed the `**FrameSearch.option` object instead of the `FrameSearch`
object