fix(rqd): add pynput in requirements
When launching RQD, there was these errors complaining of the missing
pynput package:

```text
$ CUEBOT_HOSTS="localhost" rqd
WARNING:root:CUEBOT_HOSTNAME: localhost
WARNING:root:RQD Starting Up
2022-12-08 10:04:39,643 WARNING   openrqd-__main__   RQD Starting Up
ERROR:rqd.rqnimby:Failed to import pynput, falling back to Select module
Traceback (most recent call last):
  File "D:\dev\opencue\opencue\venv\lib\site-packages\rqd-unknown-py3.10.egg\rqd\rqnimby.py", line 55, in getNimby
    import pynput
ModuleNotFoundError: No module named 'pynput'
2022-12-08 10:04:39,644 ERROR     openrqd-rqnimby    Failed to import pynput, falling back to Select module
Traceback (most recent call last):
  File "D:\dev\opencue\opencue\venv\lib\site-packages\rqd-unknown-py3.10.egg\rqd\rqnimby.py", line 55, in getNimby
    import pynput
ModuleNotFoundError: No module named 'pynput'
WARNING:rqd.rqnimby:Using Nimby nop! Something went wrong on nimby's initialization.
2022-12-08 10:04:39,652 WARNING   openrqd-rqnimby    Using Nimby nop! Something went wrong on nimby's initialization.
WARNING:rqd.rqcore:RQD Started
2022-12-08 10:04:39,690 WARNING   openrqd-rqcore     RQD Started
```

By adding pynput in requirements.txt, all the errors are now gone:

```text
$ CUEBOT_HOSTS="localhost" rqd
WARNING:root:CUEBOT_HOSTNAME: localhost
WARNING:root:RQD Starting Up
2022-12-08 09:21:13,889 WARNING   openrqd-__main__   RQD Starting Up
WARNING:rqd.rqcore:RQD Started
2022-12-08 09:21:13,958 WARNING   openrqd-rqcore     RQD Started
```