[cuegui] Fix issue on opening job comments (#1532)
CommentListDialog expects a list of jobs and at some point the input got
changed to the first job on the list.

Opening the comments dialog on the current version returns:
```
TypeError: 'Job' object is not iterable 
```